"""
Custom App Inventory Transformer

This module provides functionality to transform CSV inventory files into
a standardized JSON format for custom applications.
"""

import logging
import traceback
from typing import Dict, List, Tuple

from sdk.customapp.custom_app_models import (
    CustomAppUser, UserStatus, PrincipalType, RoleType,
    CustomAppRole, CustomAppRoleAssignment, CustomAppPermission, CustomAppInventory
)
from sdk.customapp.custom_app_utils import parse_arguments
from sdk.customapp.csv_transformer import CustomAppCsvTransformer

# Configure logging
logger = logging.getLogger(__name__)

# Constants
DEFAULT_BATCH_SIZE = 100
DEFAULT_OUTPUT_DIR = "/tmp/customapp_export"
DEFAULT_APP_NAME = "custom_app_sample"


# Example of a custom app transformer
class CustomAppSampleTransformer(CustomAppCsvTransformer):
    """Transforms CSV inventory files into standardized JSON format."""
    NON_PERMISSIONS_KEYS = {
        'id', 'isActive', 'firstName', 'lastName', 'email', 'opRoleId',
        'employeeId', 'Manager', 'Department', 'total active dates',
        'createdDate', 'updatedDate', 'Total active permissions'
    }

    @staticmethod
    def create_user(row: Dict[str, str]) -> CustomAppUser:
        """Create a user object from CSV row data."""
        username = row['email']
        user_id = row.get('employeeId') or username
        full_name = f"{row.get('firstName', '')} {row.get('lastName', '')}".strip()
        status = UserStatus.ENABLED.name if row.get('isActive', '1') == '1' \
            else UserStatus.DEACTIVATED.name
        # if status is not provided, it will be generated by the transformer based on the username
        return CustomAppUser(
            id=user_id,
            username=username,
            name=full_name,
            status=status
        )

    @staticmethod
    def create_role(app_name_prefix: str, row: Dict[str, str]) -> Tuple[str, CustomAppRole]:
        """Create a role object from CSV row data."""
        role_name = row.get('opRoleId', '').strip()
        if not role_name:
            first_name = row.get('firstName', '').lower()
            last_name = row.get('lastName', '').lower()
            role_name = f"{app_name_prefix.lower()}-{first_name}-{last_name}-role"
            role_type = RoleType.CUSTOM_APP_USER_ROLE.name
        else:
            role_type = RoleType.CUSTOM_APP_ROLE.name

        permissions = [
            key for key, value in row.items()
            if key not in CustomAppSampleTransformer.NON_PERMISSIONS_KEYS and value == 'TRUE'
        ]

        role = CustomAppRole(
            id=role_name,
            name=role_name,
            type=role_type,
            permissions=permissions
        )

        return role_name, role

    @staticmethod
    def create_role_assignment(username: str, role_name: str) -> CustomAppRoleAssignment:
        """Create a role assignment object."""
        assignment_id = f"{username}_{role_name}"
        return CustomAppRoleAssignment(
            id=assignment_id,
            principalId=username,
            principalType=PrincipalType.HUMAN.name,
            roleId=role_name
        )

    @staticmethod
    def create_permission(permission_name: str) -> CustomAppPermission:
        """Create a permission object."""
        return CustomAppPermission(name=permission_name)


    @staticmethod
    def validate_user_data(row: Dict[str, str]) -> bool:
        """Validate user data from CSV row."""
        username = row.get('email', '').strip()
        if not username:
            logger.error("Skipping row: username not set in {%s}", row)
            return False
        return True

    @staticmethod
    def validate_role_permissions(role_name: str, existing_permissions: List[str],
                                  new_permissions: List[str]) -> bool:
        """Validate role permissions consistency."""
        if existing_permissions and set(new_permissions) != set(existing_permissions):
            logger.error("Role %s has conflicting permissions: %s", role_name,
                         set(new_permissions).difference(set(existing_permissions)))
            return False
        return True

    @staticmethod
    def validate_assignment_conflict(assignment_id: str) -> bool:
        """Validate no conflicting role assignments."""
        return True  # This will be checked in the main logic

    def process_csv_row(self, row: Dict[str, str],
                         errors: List[Dict[str, str]]) -> None:
        """Process a single CSV row and update inventory."""
        # Validate user data
        inventory = self.inventory
        if not self.validate_user_data(row):
            errors.append(row)
            logger.error("Skipping row: %s as user data is not valid", row)
            return

        #import pdb; pdb.set_trace()
        username = row['email']
        # Create or update user
        user = self.create_user(row)
        inventory.users[username] = user
        # Create or update role
        role_name, role = self.create_role(self.app_name, row)

        # Validate role permissions
        if role_name in inventory.roles:
            existing_role = inventory.roles[role_name]
            if not self.validate_role_permissions(
                role_name, existing_role.permissions, role.permissions):
                errors.append(row)
                return
            # Merge permissions
            existing_role.permissions.extend(role.permissions)
            role = existing_role

        inventory.roles[role_name] = role

        # Create role assignment
        assignment = self.create_role_assignment(username, role_name)

        # Check for assignment conflicts
        if assignment.id in inventory.assignments:
            logger.error("Skipping conflicting assignment: %s", assignment.id)
            errors.append(row)
            return

        inventory.assignments[assignment.id] = assignment

        # Create permissions
        for permission_name in role.permissions:
            if permission_name not in inventory.permissions:
                permission = self.create_permission(permission_name)
                inventory.permissions[permission_name] = permission


def setup_logging() -> None:
    """Setup logging configuration."""
    logger.setLevel(logging.INFO)

    # Remove existing handlers to avoid duplicates
    for handler in logger.handlers[:]:
        logger.removeHandler(handler)

    # Create console handler
    console_handler = logging.StreamHandler()
    formatter = logging.Formatter(
        '%(asctime)s:%(levelname)s:%(module)s:%(funcName)s:%(lineno)s: %(message)s'
    )
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)


def main() -> None:
    """Main entry point for the script."""
    args = parse_arguments()
    setup_logging()

    try:
        # Create the transformer instance
        transformer = CustomAppSampleTransformer(
            app_name=args.app_name.strip(),
            inventory_file=args.inventory_file.strip(),
            output_dir=args.output_dir.strip())

        # Transform and export the inventory
        transformer.transform_and_export()
        logger.info("Transformation completed successfully")

    except Exception as e:
        logger.error("Transformation failed: {%s}", e)
        logger.error("Stack trace: %s", traceback.format_exc())
        raise


if __name__ == '__main__':
    main()
